### PR TITLE
updated dependencies to fix vulnerabilities

### LINKED ISSUE #8: Fix dependencies' vulnerabilities
https://github.com/paritytech/github-issue-sync/blob/0d1265b07649ea6319a8d8dfef9102d52e9cc644/.gitlab-ci.yml#L68 currently reports some security vulnerabilities which should be fixed

### PR DESCRIPTION
**Pull request by Bullrich**
Updated dependencies:
- eslint
- eslint-plugin-import

To remove dependencies vulnerabilities. This would partially fix #8 but there are more root problems tied to analysis.

Also, it seems `trivy` is not the best option to analyze our repository as it [doesn't differ production dependencies from dev dependencies for yarn projects](https://github.com/aquasecurity/trivy/issues/90).

Could we use `yarn audit` instead?

Also, some of our vulnerabilities in the dev dependencies are generated by [prettier-plugin-compactify](https://github.com/resolritter/prettier-plugin-compactify).

Do we need this plugin? Seems to fix a very niche problem in formatting and it has outdated dependencies that are generating

### CODE REVIEW

**Comment by mutantcornholio** [comment]
Maybe it'd be better to start using `opstooling-js-style` here?

**Comment by Bullrich** [comment]
> Maybe it'd be better to start using `opstooling-js-style` here?

This actually fixed a lot of the issues. Will commit that.

Thanks for the tip.

**Comment by Bullrich** [comment]
> Also, it seems `trivy` is not the best option to analyze our repository as it [doesn't differ production dependencies from dev dependencies for yarn projects](https://github.com/aquasecurity/trivy/issues/90).
> 
> Could we use `yarn audit` instead?

What should we do about this? Is using `yarn audit` an option?

**Comment by mutantcornholio** [comment]
> Also, it seems `trivy` is not the best option to analyze our repository as it [doesn't differ production dependencies from dev dependencies for yarn projects](https://github.com/aquasecurity/trivy/issues/90).

Actually, why not just use dependabot? For other projects it seems to work fine

**Comment by Bullrich** [comment]
> Actually, why not just use dependabot? For other projects it seems to work fine

Seems like the best course of action. I moved that task into #31 and will do it after finishing this one.

**Review by mordamax — CHANGES_REQUESTED** [review]
in gitlab-ci.yml
```
    # TODO: Use pre-commit run --all
    - echo "lint"
```

might need to be fixed so the lint indeed checked

**Review by alvicsam — APPROVED** [review]

**Review by mordamax — APPROVED** [review]

**Pull request merged**
